# model setting
model_cfg:
  # class_type: 'models.ST_GCN_18'
  in_channels: 1024
  nhid: 256
  num_class: 2
  dropout: 0.4
  alpha: 0.2
  nheads: 8

# dataset setting
dataset_cfg:
  # class_type: 'dataset.DataFeeder'
  data_path: './data/detection_res_1218/training/'
  # data_path: './data/detection_res_1120/training/'
  # data_path: './data/processed_data_1020/training/'

# dataloader setting
batch_size: 1
gpus: 1

# optimizer setting
optimizer_cfg:
  lr: 0.0005

# runtime setting
total_epochs: 40
training_hooks:
  lr_step: [10, 50]
  checkpoint_interval: 1
resume_from:
load_from:
checkpoint_path: 'models/predictor_t1005/'